/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/VYJ7tbcyipf
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Calendar } from "@/components/ui/calendar"
import { Button } from "@/components/ui/button"

export function Component() {
  return (
    <div className="flex flex-col h-screen">
      <header className="bg-primary text-primary-foreground py-4 px-6">
        <h1 className="text-2xl font-bold">Plant Care Calendar</h1>
      </header>
      <main className="flex-1 bg-background p-4 sm:p-6">
        <div className="grid grid-cols-1 gap-4 sm:grid-cols-7 sm:gap-6">
          <div className="col-span-1 sm:col-span-5">
            <Calendar className="w-full aspect-[4/3]" />
          </div>
          <div className="col-span-1 bg-card rounded-lg p-4 shadow-md sm:col-span-2">
            <h2 className="text-lg font-bold mb-4">Upcoming Tasks</h2>
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <div>
                  <h3 className="font-medium">Water Plants</h3>
                  <p className="text-muted-foreground text-sm">Tomorrow</p>
                </div>
                <Button variant="outline" size="sm">
                  <CheckIcon className="w-4 h-4 mr-2" />
                  Done
                </Button>
              </div>
              <div className="flex items-center justify-between">
                <div>
                  <h3 className="font-medium">Fertilize Roses</h3>
                  <p className="text-muted-foreground text-sm">Friday</p>
                </div>
                <Button variant="outline" size="sm">
                  <CheckIcon className="w-4 h-4 mr-2" />
                  Done
                </Button>
              </div>
              <div className="flex items-center justify-between">
                <div>
                  <h3 className="font-medium">Prune Tomato Plants</h3>
                  <p className="text-muted-foreground text-sm">Next Sunday</p>
                </div>
                <Button variant="outline" size="sm">
                  <CheckIcon className="w-4 h-4 mr-2" />
                  Done
                </Button>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}

function CheckIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 6 9 17l-5-5" />
    </svg>
  )
}


function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
